### ISSUE TITLE
`upgrade_unit` does match signature of abstract method

### ISSUE THREAD

**Issue by carlcsaposs-canonical** [canonical/mysql-router-operator#139]
Mismatch between
upgrade_unit call in abstract_charm.py (type hinting is for abstract upgrade.py)
https://github.com/canonical/mysql-router-operator/blob/b27eafef502c1286b299c107fc4e68b99e74d0d8/src/abstract_charm.py#L273-L278

upgrade.py abstract `upgrade_unit`
https://github.com/canonical/mysql-router-operator/blob/b27eafef502c1286b299c107fc4e68b99e74d0d8/src/upgrade.py#L231-L236

machine_upgrade.py `upgrade_unit`
https://github.com/canonical/mysql-router-operator/blob/b27eafef502c1286b299c107fc4e68b99e74d0d8/src/machine_upgrade.py#L161-L168

**Comment by shayancanonical** [comment]
resolved in https://github.com/canonical/mysql-router-operator/pull/135
